flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.2.0
- authenticate-oauth-1.5.1.2
- base-orphans-0.6
- persistent-2.7.0
- primitive-0.6.2.0
- semigroupoids-5.2
- vector-0.12.0.1
- yesod-auth-oauth-1.4.2
resolver: lts-8.13
